### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by kremalicious** [DEX-Company/starfish-js#9]
What functionality is intended to be added here which can't be done with squid-js? Is it solving a specific Dex use case only? Is it intended for Ocean Protocol community? Why not contribute new features to squid-js instead?

For all users coming to this repo from Google: use Ocean Protocol's official client to connect to one of the networks with JavaScript: https://github.com/oceanprotocol/squid-js

The readme of this repo should clearly state the relationship of this library to squid-js and what sets it apart. If the feature set turns out to be the same, then, well, this repo seems pointless and just adds confusion to the outside world.

**Comment by mikera** [comment]
Starfish is a developer toolkit for building decentralised data solutions. It is a higher level library than Squid - As a potentially useful analogy with the Linux Operating System, Starfish might be regarded as equivalent to the VFS, whereas Squid is a specific filesystem.

Starfish works with open standards defined in Data Ecosystem Proposals, and forms part of the overall data ecosystem architecture as defined in DEP3:
https://github.com/DEX-Company/DEPs/tree/master/3

Starfish is designed to work with the Ocean Network where users wish to do so. In cases where specific Ocean Network functionality is required, starfish delegates to Squid (i.e. Squid is a dependency of Starfish). Developers who do not wish to use Squid directly, but still want to access capabilities of the Ocean Network, may choose to use Starfish.

**Comment by kremalicious** [comment]
Don't tell just me, tell the world :-)

> The readme of this repo should clearly state...

The readme should be made less confusing:
- so how do I use and install this library in my projects?
- TOC and content are out of sync
- linking the squid-js badge to actual squid-js instead of squid-py
- how does testing work? Readme says something about `tox`, and "Our test use npm framework". Project is setup to test with Mocha as far as I can see
- `npm start` tries to link `@dex/starfish-js` package, but it doesn't exist
- how do I connect to different Ocean networks?

And maybe tell people why they should use that forked barge version with outdated components instead of latest upstream repo.
